# Generated by Django 5.1.3 on 2024-11-27 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_createusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_seguindo', models.DateTimeField(auto_now_add=True)),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo', to='api_rest.usuario')),
                ('seguindo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='api_rest.usuario')),
            ],
            options={
                'unique_together': {('seguidor', 'seguindo')},
            },
        ),
        migrations.DeleteModel(
            name='Createusuario',
        ),
    ]
