# Generated by Django 5.1.3 on 2024-11-27 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_postagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='atualizado_em',
        ),
        migrations.AlterField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_curtiu', models.DateTimeField(auto_now_add=True)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.postagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'postagem')},
            },
        ),
    ]
