# Generated by Django 5.1.3 on 2024-11-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_remove_postagem_atualizado_em_alter_postagem_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='curtida',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='curtida',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='api_rest.postagem'),
        ),
        migrations.AlterField(
            model_name='curtida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='api_rest.usuario'),
        ),
        migrations.AddConstraint(
            model_name='curtida',
            constraint=models.UniqueConstraint(fields=('usuario', 'postagem'), name='unique_usuario_postagem'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api_rest.postagem'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api_rest.usuario'),
        ),
    ]
